tools:
    php_mess_detector: true
    php_code_sniffer: true
    sensiolabs_security_checker: true
    php_pdepend: true
    php_loc:
        enabled: true
        excluded_dirs: [vendor, tests]
filter:
    excluded_paths:
        - 'tests/*'
build:
    environment:
        php: 7.2.13
    tests:
      override:
        - command: vendor/bin/phpunit --coverage-clover="build/logs/clover.xml"
          coverage:
            file: build/logs/clover.xml
            format: clover
